---
- name: Deploy the agent
  hosts: all
  become: true
  gather_facts: false

  vars:
    program_name: agent-e5573

  tasks:
  - name: Program binary is up-to-date
    copy:
      src: "{{ playbook_dir }}/../{{ program_name }}"
      dest: "/usr/local/bin/{{ program_name }}"
      mode: "0755"
    tags: [ copy, binary ]

  - name: Systemd timer is present
    template:
      src: "{{ program_name }}.timer.j2"
      dest: "/etc/systemd/system/{{ program_name }}.timer"
      mode: "0664"
    tags: systemd

  - name: Systemd service is present
    template:
      src: "{{ program_name }}.service.j2"
      dest: "/etc/systemd/system/{{ program_name }}.service"
      mode: "0664"
    tags: systemd

  - name: Service is started and enabled
    systemd:
      name: "{{ program_name }}.service"
      state: started
      enabled: true
    tags: [ systemd, service ]

  - name: Timer is started and enabled
    systemd:
      name: "{{ program_name }}.timer"
      state: started
      enabled: true
    tags: [ systemd, timer ]

  - name: Register version of the deployed binary
    command: "/usr/local/bin/{{ program_name }} --version"
    register: program_version
    tags: [ version ]

  - name: System packages are installed
    apt:
      name:
        - python-pip
        - python-setuptools
      state: present
      update_cache: true
    tags: apt, pip, python, influxdb

  - name: Python modules are present
    pip:
      name:
      - influxdb
    tags: [ influxdb, python, pip ]

  - name: Write deployment event info
    influxdb_write:
      hostname: "{{ influxdb_host }}"
      ssl: "{{ influxdb_tls }}"
      use_udp: false
      udp_port: 4444
      port: "{{ influxdb_port }}"
      username: "{{ influxdb_user }}"
      password: "{{ influxdb_user_password }}"
      database_name: "{{influxdb_database}}"
      data_points:
        - measurement: events
          tags:
            host: "{{ inventory_hostname }}"
          fields:
            title: "Deployment of {{ program_name }} {{ program_version.stdout }}"
    tags: [ influxdb, events ]
